"""Baseline schema (squashed).

Revision ID: 0001_baseline
Revises: (none)
Create Date: 2026-10-04

Replaces the old 001..012 / hash-named chain, which could not be applied to an
empty database and had drifted from the models. Generated with
``alembic revision --autogenerate`` against an empty MariaDB and reviewed.
Existing databases: see ``alembic/README_MIGRATIONS.md``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "game_accounts",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("server_url", sa.String(length=200), nullable=False),
        sa.Column("server_name", sa.String(length=50), nullable=True),
        sa.Column("server_speed", sa.Integer(), nullable=False),
        sa.Column(
            "tribe",
            sa.Enum(
                "romans",
                "gauls",
                "teutons",
                "huns",
                "egyptians",
                "vikings",
                "spartans",
                name="tribetype",
            ),
            nullable=True,
        ),
        sa.Column("player_name", sa.String(length=50), nullable=True),
        sa.Column("alliance_name", sa.String(length=50), nullable=True),
        sa.Column(
            "server_start_date",
            sa.Date(),
            nullable=True,
            comment="伺服器/帳號開始日期，用於計算遊戲天數",
        ),
        sa.Column(
            "player_role",
            sa.Enum("attacker", "defender", "farmer", "hybrid", name="playerrole"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh_key", sa.String(length=500), nullable=False),
        sa.Column("auth_key", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    op.create_table(
        "battle_reports",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column(
            "travian_report_id",
            sa.String(length=50),
            nullable=True,
            comment="Travian 遊戲內的報告 ID",
        ),
        sa.Column(
            "report_type", sa.String(length=20), nullable=False, comment="報告類型"
        ),
        sa.Column("title", sa.String(length=255), nullable=True, comment="報告標題"),
        sa.Column("is_read", sa.Boolean(), nullable=False, comment="是否已讀"),
        sa.Column("battle_time", sa.DateTime(), nullable=True, comment="戰鬥發生時間"),
        sa.Column(
            "attacker_troops",
            mysql.JSON(),
            nullable=True,
            comment="進攻方部隊配置 JSON",
        ),
        sa.Column(
            "defender_troops",
            mysql.JSON(),
            nullable=True,
            comment="防守方部隊配置 JSON",
        ),
        sa.Column(
            "attacker_losses", mysql.JSON(), nullable=True, comment="進攻方損失 JSON"
        ),
        sa.Column(
            "defender_losses", mysql.JSON(), nullable=True, comment="防守方損失 JSON"
        ),
        sa.Column("result", sa.String(length=20), nullable=True, comment="戰鬥結果"),
        sa.Column(
            "resources_stolen", mysql.JSON(), nullable=True, comment="掠奪資源 JSON"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["game_accounts.account_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("report_id"),
        sa.UniqueConstraint("travian_report_id"),
    )
    op.create_table(
        "map_snapshots",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("server_url", sa.String(length=200), nullable=False),
        sa.Column("total_villages", sa.Integer(), nullable=False),
        sa.Column("total_players", sa.Integer(), nullable=False),
        sa.Column("total_alliances", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["game_accounts.account_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_table(
        "reminder_rules",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column(
            "reminder_type",
            sa.Enum(
                "BUILD_COMPLETE",
                "TRAIN_COMPLETE",
                "RESOURCE_FULL",
                "HERO_READY",
                "ATTACK_INCOMING",
                "CUSTOM",
                name="remindertype",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "threshold", sa.Integer(), nullable=True, comment="閾值（如資源滿倉百分比）"
        ),
        sa.Column(
            "description", sa.String(length=200), nullable=True, comment="規則描述"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["game_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_table(
        "villages",
        sa.Column("village_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("travian_village_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("coordinate_x", sa.Integer(), nullable=True),
        sa.Column("coordinate_y", sa.Integer(), nullable=True),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column(
            "village_type",
            sa.Enum("4-4-4-6", "3-4-5-6", "15c", "9c", "7c", "6c", name="villagetype"),
            nullable=True,
        ),
        sa.Column("is_capital", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "capital",
                "hammer",
                "anvil",
                "resource",
                "mixed",
                "ww",
                name="villagerole",
            ),
            nullable=True,
        ),
        sa.Column("wood", sa.Integer(), nullable=False),
        sa.Column("clay", sa.Integer(), nullable=False),
        sa.Column("iron", sa.Integer(), nullable=False),
        sa.Column("crop", sa.Integer(), nullable=False),
        sa.Column("wood_production", sa.Integer(), nullable=False),
        sa.Column("clay_production", sa.Integer(), nullable=False),
        sa.Column("iron_production", sa.Integer(), nullable=False),
        sa.Column("crop_production", sa.Integer(), nullable=False),
        sa.Column("warehouse_capacity", sa.Integer(), nullable=False),
        sa.Column("granary_capacity", sa.Integer(), nullable=False),
        sa.Column("cp_per_day", sa.Integer(), nullable=False),
        sa.Column("merchants_used", sa.Integer(), nullable=False),
        sa.Column("merchants_total", sa.Integer(), nullable=False),
        sa.Column("total_troops", sa.Integer(), nullable=False),
        sa.Column("has_incoming_attack", sa.Boolean(), nullable=False),
        sa.Column("attack_count", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["game_accounts.account_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("village_id"),
    )
    op.create_index(
        op.f("ix_villages_travian_village_id"),
        "villages",
        ["travian_village_id"],
        unique=False,
    )
    op.create_table(
        "building_instances",
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("village_id", sa.String(length=36), nullable=False),
        sa.Column(
            "building_id",
            sa.String(length=50),
            nullable=False,
            comment="建築類型 ID（對應 buildings.json）",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=True,
            comment="建築在村莊中的位置（1-40）",
        ),
        sa.Column("current_level", sa.Integer(), nullable=False),
        sa.Column("is_upgrading", sa.Boolean(), nullable=False),
        sa.Column("upgrade_finish_time", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["village_id"], ["villages.village_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.create_table(
        "map_alliances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("travian_alliance_id", sa.Integer(), nullable=False),
        sa.Column("alliance_name", sa.String(length=100), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("total_population", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["map_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_map_alliances_snapshot_id",
        "map_alliances",
        ["snapshot_id", "travian_alliance_id"],
        unique=False,
    )
    op.create_table(
        "map_conquests",
        sa.Column("conquest_id", sa.String(length=36), nullable=False),
        sa.Column("server_url", sa.String(length=255), nullable=False),
        sa.Column("detected_at_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("village_name", sa.String(length=255), nullable=True),
        sa.Column("village_x", sa.Integer(), nullable=False),
        sa.Column("village_y", sa.Integer(), nullable=False),
        sa.Column("old_player_id", sa.Integer(), nullable=True),
        sa.Column("old_player_name", sa.String(length=255), nullable=True),
        sa.Column("old_alliance_name", sa.String(length=255), nullable=True),
        sa.Column("new_player_id", sa.Integer(), nullable=True),
        sa.Column("new_player_name", sa.String(length=255), nullable=True),
        sa.Column("new_alliance_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["detected_at_snapshot_id"],
            ["map_snapshots.snapshot_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("conquest_id"),
    )
    op.create_index(
        op.f("ix_map_conquests_server_url"),
        "map_conquests",
        ["server_url"],
        unique=False,
    )
    op.create_index(
        "ix_map_conquests_snapshot_id",
        "map_conquests",
        ["detected_at_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "map_name_changes",
        sa.Column("change_id", sa.String(length=36), nullable=False),
        sa.Column("server_url", sa.String(length=255), nullable=False),
        sa.Column("detected_at_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("old_name", sa.String(length=255), nullable=False),
        sa.Column("new_name", sa.String(length=255), nullable=False),
        sa.Column("game_day", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["detected_at_snapshot_id"],
            ["map_snapshots.snapshot_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("change_id"),
    )
    op.create_index(
        op.f("ix_map_name_changes_server_url"),
        "map_name_changes",
        ["server_url"],
        unique=False,
    )
    op.create_index(
        "ix_map_name_changes_snapshot_id",
        "map_name_changes",
        ["detected_at_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "map_players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("travian_player_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("travian_alliance_id", sa.Integer(), nullable=True),
        sa.Column("alliance_name", sa.String(length=100), nullable=True),
        sa.Column("village_count", sa.Integer(), nullable=False),
        sa.Column("total_population", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["map_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_map_players_snapshot_id",
        "map_players",
        ["snapshot_id", "travian_player_id"],
        unique=False,
    )
    op.create_table(
        "map_server_stats",
        sa.Column("stats_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("server_url", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total_players", sa.Integer(), nullable=False),
        sa.Column("active_players", sa.Integer(), nullable=False),
        sa.Column("total_villages", sa.Integer(), nullable=False),
        sa.Column("total_alliances", sa.Integer(), nullable=False),
        sa.Column("total_population", sa.BigInteger(), nullable=False),
        sa.Column("new_players", sa.Integer(), nullable=False),
        sa.Column("deleted_players", sa.Integer(), nullable=False),
        sa.Column("villages_settled", sa.Integer(), nullable=False),
        sa.Column("villages_destroyed", sa.Integer(), nullable=False),
        sa.Column("conquests_today", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["map_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("stats_id"),
    )
    op.create_index(
        op.f("ix_map_server_stats_server_url"),
        "map_server_stats",
        ["server_url"],
        unique=False,
    )
    op.create_index(
        "ix_map_server_stats_snapshot_id",
        "map_server_stats",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "map_villages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("travian_village_id", sa.Integer(), nullable=False),
        sa.Column("village_name", sa.String(length=100), nullable=True),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("field_type", sa.Integer(), nullable=False),
        sa.Column("travian_player_id", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(length=100), nullable=True),
        sa.Column("travian_alliance_id", sa.Integer(), nullable=True),
        sa.Column("alliance_name", sa.String(length=100), nullable=True),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("is_capital", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["map_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_map_villages_snapshot_coords",
        "map_villages",
        ["snapshot_id", "x", "y"],
        unique=False,
    )
    op.create_index(
        "ix_map_villages_snapshot_player",
        "map_villages",
        ["snapshot_id", "travian_player_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("notification_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("rule_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "BUILD_COMPLETE",
                "TRAIN_COMPLETE",
                "RESOURCE_FULL",
                "HERO_READY",
                "ATTACK_INCOMING",
                "CUSTOM",
                name="remindertype",
            ),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_pushed", sa.Boolean(), nullable=False, comment="是否已推播"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["game_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["reminder_rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_table(
        "sync_logs",
        sa.Column("log_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("village_id", sa.String(length=36), nullable=True),
        sa.Column(
            "sync_type",
            sa.Enum(
                "VILLAGE_OVERVIEW",
                "VILLAGE_CENTER",
                "TROOPS",
                "FULL",
                "MAP_SQL",
                name="synctype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "PARTIAL", "FAILED", name="syncstatus"),
            nullable=False,
        ),
        sa.Column("items_synced", sa.Integer(), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("conflicts_resolved", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["game_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["villages.village_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "troop_instances",
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("village_id", sa.String(length=36), nullable=False),
        sa.Column(
            "troop_id",
            sa.String(length=50),
            nullable=False,
            comment="部隊類型 ID（對應 troops.json）",
        ),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            sa.String(length=20),
            nullable=False,
            comment="部隊位置狀態: home/training/away",
        ),
        sa.Column("is_training", sa.Boolean(), nullable=False),
        sa.Column("training_finish_time", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["village_id"], ["villages.village_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table drops its indexes; on MySQL an index backing a foreign
    # key cannot be dropped on its own, so only tables are dropped (children
    # first).
    op.drop_table("troop_instances")
    op.drop_table("sync_logs")
    op.drop_table("notifications")
    op.drop_table("map_villages")
    op.drop_table("map_server_stats")
    op.drop_table("map_players")
    op.drop_table("map_name_changes")
    op.drop_table("map_conquests")
    op.drop_table("map_alliances")
    op.drop_table("building_instances")
    op.drop_table("villages")
    op.drop_table("reminder_rules")
    op.drop_table("map_snapshots")
    op.drop_table("battle_reports")
    op.drop_table("push_subscriptions")
    op.drop_table("game_accounts")
    op.drop_table("users")
    # ### end Alembic commands ###
