"""Travian 部族資料庫.

兵種速度不寫在這裡：由 scripts/game_data/gen_game_data.py 產生到
backend/data/static/unit_speeds.json（P0-15，ts11 遊戲內說明／官方文章），
模組載入時用 _apply_unit_speeds() 帶入。沒有第一手出處的兵種速度是 None（待驗證）。
運載量也一樣由產生器帶入（P0-23），這個檔案不寫；維京是 None（還沒核對）。
其餘兵種數值（攻防、花費、糧耗、訓練時間）尚未重建，見 docs/TICKETS.md P0-15。
"""

import json
from pathlib import Path
from typing import Any

UNIT_SPEEDS_PATH = (
    Path(__file__).resolve().parents[2] / "data" / "static" / "unit_speeds.json"
)
# 部族、兵種中文名一律讀遊戲內名稱表（#34 PM）：這個檔案裡寫的名字只是佔位，載入時蓋掉
INGAME_NAMES_PATH = (
    Path(__file__).resolve().parents[2] / "data" / "static" / "ingame_names.json"
)

TRIBES_DATA: dict[str, dict[str, Any]] = {
    "romans": {
        "name_zh": "羅馬",
        "name_en": "Romans",
        "description": "可以同時升級建築物和資源田，擁有強大但昂貴的軍隊",
        "playstyle": "適合新手，平衡型發展",
        "strengths": [
            "可同時建造建築物和資源田（雙建）",
            "步兵防禦力極強（禁衛兵是最佳反步兵單位）",
            "騎兵攻擊力高（帝國騎士攻擊力最高）",
            "英雄每點力量+100（其他部族+80）",
        ],
        "weaknesses": [
            "部隊訓練成本高、時間長",
            "掠奪效率差（古羅馬步兵速度慢、載重小）",
            "禁衛兵對騎兵防禦力弱",
            "禁衛兵移動速度慢，不適合遠距離支援",
        ],
        "special_building": {
            "name": "放牧水槽 (Horse Drinking Trough)",
            "effect": "每升一級減少騎兵1%的糧食消耗，最高減少20%",
        },
        "merchant": {"capacity": 500, "speed": 16},
        "hero_bonus": "每點力量屬性+100（而非標準的+80）",
        "recommended_defense_ratio": "70% 禁衛兵 / 30% 古羅馬步兵",
        "troops": {
            "legionnaire": {
                "name_zh": "古羅馬步兵",
                "type": "infantry",
                "attack": 40,
                "defense_infantry": 35,
                "defense_cavalry": 50,
                "upkeep": 1,
                "cost": {"wood": 120, "clay": 100, "iron": 150, "crop": 30},
                "training_time": "0:26:40",
                "role": "多功能步兵，攻防兼備",
            },
            "praetorian": {
                "name_zh": "禁衛兵",
                "type": "infantry",
                "attack": 30,
                "defense_infantry": 65,
                "defense_cavalry": 35,
                "upkeep": 1,
                "cost": {"wood": 100, "clay": 130, "iron": 160, "crop": 70},
                "training_time": "0:29:20",
                "role": "最強反步兵防禦單位",
            },
            "imperian": {
                "name_zh": "帝國兵",
                "type": "infantry",
                "attack": 70,
                "defense_infantry": 40,
                "defense_cavalry": 25,
                "upkeep": 1,
                "cost": {"wood": 150, "clay": 160, "iron": 210, "crop": 80},
                "training_time": "0:32:00",
                "role": "主力攻擊步兵",
            },
            "equites_legati": {
                "name_zh": "使者騎士",
                "type": "cavalry",
                "attack": 0,
                "defense_infantry": 20,
                "defense_cavalry": 10,
                "upkeep": 2,
                "cost": {"wood": 140, "clay": 160, "iron": 20, "crop": 40},
                "training_time": "0:28:00",
                "role": "偵察兵",
            },
            "equites_imperatoris": {
                "name_zh": "帝國騎士",
                "type": "cavalry",
                "attack": 120,
                "defense_infantry": 65,
                "defense_cavalry": 50,
                "upkeep": 3,
                "cost": {"wood": 550, "clay": 440, "iron": 320, "crop": 100},
                "training_time": "0:50:00",
                "role": "輕騎兵，適合掠奪",
            },
            "equites_caesaris": {
                "name_zh": "將軍騎士",
                "type": "cavalry",
                "attack": 180,
                "defense_infantry": 80,
                "defense_cavalry": 105,
                "upkeep": 4,
                "cost": {"wood": 550, "clay": 640, "iron": 800, "crop": 180},
                "training_time": "1:10:00",
                "role": "重騎兵，最強攻擊力但糧食消耗高",
            },
            "battering_ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 60,
                "defense_infantry": 30,
                "defense_cavalry": 75,
                "upkeep": 3,
                "cost": {"wood": 900, "clay": 360, "iron": 500, "crop": 70},
                "training_time": "1:00:00",
                "role": "破壞城牆",
            },
            "fire_catapult": {
                "name_zh": "火焰投石機",
                "type": "siege",
                "attack": 75,
                "defense_infantry": 60,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 950, "clay": 1350, "iron": 600, "crop": 90},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "senator": {
                "name_zh": "參議員",
                "type": "special",
                "attack": 50,
                "defense_infantry": 40,
                "defense_cavalry": 30,
                "upkeep": 5,
                "cost": {"wood": 30750, "clay": 27200, "iron": 45000, "crop": 37500},
                "training_time": "18:30:00",
                "role": "降低敵方村莊忠誠度 20-30%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 0,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 4600, "clay": 4200, "iron": 5800, "crop": 4400},
                "training_time": "8:36:40",
                "role": "建立新村莊",
            },
        },
    },
    "gauls": {
        "name_zh": "高盧",
        "name_en": "Gauls",
        "description": "擁有遊戲中最快的部隊，防禦能力強，適合防守或快速突襲",
        "playstyle": "適合新手，防禦為主但也可攻擊",
        "strengths": [
            "擁有遊戲中最快的單位（德魯伊騎兵、探路者、雷法師）",
            "山洞容量是其他部族的1.5倍",
            "方陣兵是最佳的全能防禦步兵",
            "商人速度快（24格/小時）",
        ],
        "weaknesses": [
            "破城槌是所有部族中最弱的",
            "不適合建造世界奇觀攻擊部隊",
            "攻擊力相對較弱",
        ],
        "special_building": {
            "name": "陷阱機 (Trapper)",
            "effect": "可以製造陷阱捕捉敵方部隊，最多可捕捉200單位（英雄等級20時400）",
        },
        "merchant": {"capacity": 750, "speed": 24},
        "hero_bonus": "騎乘時速度+5格/小時",
        "recommended_defense_ratio": "70% 方陣兵 / 30% 德魯伊騎兵",
        "troops": {
            "phalanx": {
                "name_zh": "方陣兵",
                "type": "infantry",
                "attack": 15,
                "defense_infantry": 40,
                "defense_cavalry": 50,
                "upkeep": 1,
                "cost": {"wood": 100, "clay": 130, "iron": 55, "crop": 30},
                "training_time": "0:17:00",
                "role": "主力防禦步兵，訓練快速且便宜",
            },
            "swordsman": {
                "name_zh": "劍士",
                "type": "infantry",
                "attack": 65,
                "defense_infantry": 35,
                "defense_cavalry": 20,
                "upkeep": 1,
                "cost": {"wood": 140, "clay": 150, "iron": 185, "crop": 60},
                "training_time": "0:26:00",
                "role": "攻擊步兵",
            },
            "pathfinder": {
                "name_zh": "探路者",
                "type": "cavalry",
                "attack": 0,
                "defense_infantry": 20,
                "defense_cavalry": 10,
                "upkeep": 2,
                "cost": {"wood": 170, "clay": 150, "iron": 20, "crop": 40},
                "training_time": "0:26:40",
                "role": "偵察兵，速度極快",
            },
            "theutates_thunder": {
                "name_zh": "雷法師",
                "type": "cavalry",
                "attack": 90,
                "defense_infantry": 25,
                "defense_cavalry": 40,
                "upkeep": 2,
                "cost": {"wood": 350, "clay": 450, "iron": 230, "crop": 60},
                "training_time": "0:37:20",
                "role": "快速掠奪騎兵，遊戲中第三快的單位",
            },
            "druidrider": {
                "name_zh": "德魯伊騎兵",
                "type": "cavalry",
                "attack": 45,
                "defense_infantry": 115,
                "defense_cavalry": 55,
                "upkeep": 2,
                "cost": {"wood": 360, "clay": 330, "iron": 280, "crop": 120},
                "training_time": "0:40:00",
                "role": "快速防禦騎兵，最佳反步兵防禦騎兵",
            },
            "haeduan": {
                "name_zh": "海頓聖騎",
                "type": "cavalry",
                "attack": 140,
                "defense_infantry": 60,
                "defense_cavalry": 165,
                "upkeep": 3,
                "cost": {"wood": 500, "clay": 620, "iron": 675, "crop": 170},
                "training_time": "0:53:20",
                "role": "重騎兵，高攻擊力且對騎兵防禦強",
            },
            "ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 50,
                "defense_infantry": 30,
                "defense_cavalry": 105,
                "upkeep": 3,
                "cost": {"wood": 690, "clay": 540, "iron": 660, "crop": 130},
                "training_time": "1:15:00",
                "role": "破壞城牆（所有部族中最弱）",
            },
            "trebuchet": {
                "name_zh": "投石類攻城武器",
                "type": "siege",
                "attack": 70,
                "defense_infantry": 45,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 960, "clay": 1450, "iron": 630, "crop": 90},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "chieftain": {
                "name_zh": "族長",
                "type": "special",
                "attack": 40,
                "defense_infantry": 50,
                "defense_cavalry": 50,
                "upkeep": 4,
                "cost": {"wood": 30750, "clay": 45400, "iron": 31000, "crop": 37500},
                "training_time": "18:30:00",
                "role": "降低敵方村莊忠誠度 20-25%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 0,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 5500, "clay": 7000, "iron": 5300, "crop": 4900},
                "training_time": "10:00:00",
                "role": "建立新村莊",
            },
        },
    },
    "teutons": {
        "name_zh": "日耳曼人",
        "name_en": "Teutons",
        "description": "最具侵略性的部族，部隊便宜且訓練快速，商人載重量最大",
        "playstyle": "適合積極掠奪的玩家",
        "strengths": [
            "棍棒兵是最便宜、訓練最快的單位，早期掠奪之王",
            "商人載重量最大（1000資源）",
            "偵察兵在兵營訓練（不需要馬廄），可快速獲得",
            "矛兵是最佳反騎兵防禦單位",
        ],
        "weaknesses": [
            "整體部隊移動速度較慢",
            "防禦力較弱，缺乏強力反步兵單位",
            "後期軍隊可能不如羅馬和高盧強大",
        ],
        "special_building": {
            "name": "釀酒廠 (Brewery)",
            "effect": "提升攻擊力，但會減少農作物產量",
        },
        "merchant": {"capacity": 1000, "speed": 12},
        "hero_bonus": "帶領的軍隊在掠奪時有20%的山洞穿透（可掠奪藏在山洞的資源）",
        "recommended_defense_ratio": "75% 矛兵 / 25% 遊俠",
        "troops": {
            "clubswinger": {
                "name_zh": "棍棒兵",
                "type": "infantry",
                "attack": 40,
                "defense_infantry": 20,
                "defense_cavalry": 5,
                "upkeep": 1,
                "cost": {"wood": 95, "clay": 75, "iron": 40, "crop": 40},
                "training_time": "0:12:36",
                "role": "最強早期掠奪單位，成本最低訓練最快",
            },
            "spearman": {
                "name_zh": "矛兵",
                "type": "infantry",
                "attack": 10,
                "defense_infantry": 35,
                "defense_cavalry": 60,
                "upkeep": 1,
                "cost": {"wood": 145, "clay": 70, "iron": 85, "crop": 40},
                "training_time": "0:16:40",
                "role": "最強反騎兵防禦單位",
            },
            "axeman": {
                "name_zh": "斧頭兵",
                "type": "infantry",
                "attack": 60,
                "defense_infantry": 30,
                "defense_cavalry": 30,
                "upkeep": 1,
                "cost": {"wood": 130, "clay": 120, "iron": 170, "crop": 70},
                "training_time": "0:22:00",
                "role": "主力攻擊步兵",
            },
            "scout": {
                "name_zh": "偵察兵",
                "type": "infantry",
                "attack": 0,
                "defense_infantry": 10,
                "defense_cavalry": 5,
                "upkeep": 1,
                "cost": {"wood": 160, "clay": 100, "iron": 50, "crop": 50},
                "training_time": "0:13:20",
                "role": "偵察（在兵營訓練，不需馬廄）",
            },
            "paladin": {
                "name_zh": "遊俠",
                "type": "cavalry",
                "attack": 55,
                "defense_infantry": 100,
                "defense_cavalry": 40,
                "upkeep": 2,
                "cost": {"wood": 370, "clay": 270, "iron": 290, "crop": 75},
                "training_time": "0:33:20",
                "role": "防禦騎兵，強大的反步兵能力",
            },
            "teutonic_knight": {
                "name_zh": "條頓騎士",
                "type": "cavalry",
                "attack": 150,
                "defense_infantry": 50,
                "defense_cavalry": 75,
                "upkeep": 3,
                "cost": {"wood": 450, "clay": 515, "iron": 480, "crop": 80},
                "training_time": "0:44:00",
                "role": "重騎兵，中後期掠奪主力",
            },
            "ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 65,
                "defense_infantry": 30,
                "defense_cavalry": 80,
                "upkeep": 3,
                "cost": {"wood": 1000, "clay": 300, "iron": 350, "crop": 70},
                "training_time": "1:00:00",
                "role": "破壞城牆",
            },
            "catapult": {
                "name_zh": "投石類攻城武器",
                "type": "siege",
                "attack": 50,
                "defense_infantry": 60,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 900, "clay": 1200, "iron": 600, "crop": 60},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "chief": {
                "name_zh": "司令官",
                "type": "special",
                "attack": 40,
                "defense_infantry": 60,
                "defense_cavalry": 40,
                "upkeep": 4,
                "cost": {"wood": 35500, "clay": 26600, "iron": 25000, "crop": 27200},
                "training_time": "15:23:20",
                "role": "降低敵方村莊忠誠度 20-25%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 10,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 5800, "clay": 4400, "iron": 4600, "crop": 5200},
                "training_time": "8:23:20",
                "role": "建立新村莊",
            },
        },
    },
    "egyptians": {
        "name_zh": "埃及",
        "name_en": "Egyptians",
        "description": "經濟和防禦大師，擁有遊戲中最強的經濟能力",
        "playstyle": "適合喜歡發展經濟和防禦的玩家",
        "strengths": [
            "英雄資源產出加成最高",
            "供水系統可增加綠洲加成",
            "基礎單位便宜且訓練快速",
            "防禦部隊強大，石牆耐久度高",
        ],
        "weaknesses": [
            "攻擊力較弱",
            "缺乏強力攻擊單位",
        ],
        "special_building": {
            "name": "供水系統 (Waterworks)",
            "effect": "增加綠洲對村莊的資源加成",
        },
        "merchant": {"capacity": 750, "speed": 16},
        "hero_bonus": "增加資源產出",
        "recommended_defense_ratio": "平衡防禦配置",
        "troops": {
            "slave_militia": {
                "name_zh": "奴隸民兵",
                "type": "infantry",
                "attack": 10,
                "defense_infantry": 30,
                "defense_cavalry": 25,
                "upkeep": 1,
                "cost": {"wood": 45, "clay": 60, "iron": 30, "crop": 15},
                "training_time": "0:09:30",
                "role": "最便宜的防禦單位，但糧食效率低",
            },
            "ash_warden": {
                "name_zh": "看守人艾什",
                "type": "infantry",
                "attack": 20,
                "defense_infantry": 55,
                "defense_cavalry": 40,
                "upkeep": 1,
                "cost": {"wood": 115, "clay": 100, "iron": 145, "crop": 60},
                "training_time": "0:22:00",
                "role": "主力防禦步兵",
            },
            "khopesh_warrior": {
                "name_zh": "斧刀勇士",
                "type": "infantry",
                "attack": 65,
                "defense_infantry": 50,
                "defense_cavalry": 20,
                "upkeep": 1,
                "cost": {"wood": 170, "clay": 180, "iron": 220, "crop": 80},
                "training_time": "0:27:00",
                "role": "攻擊步兵",
            },
            "sopdu_explorer": {
                "name_zh": "探險者索普杜",
                "type": "cavalry",
                "attack": 0,
                "defense_infantry": 20,
                "defense_cavalry": 10,
                "upkeep": 1,
                "cost": {"wood": 170, "clay": 150, "iron": 20, "crop": 40},
                "training_time": "0:23:20",
                "role": "偵察兵",
            },
            "anhur_guard": {
                "name_zh": "守衛安赫",
                "type": "cavalry",
                "attack": 50,
                "defense_infantry": 110,
                "defense_cavalry": 50,
                "upkeep": 2,
                "cost": {"wood": 360, "clay": 330, "iron": 280, "crop": 120},
                "training_time": "0:36:40",
                "role": "防禦騎兵",
            },
            "resheph_chariot": {
                "name_zh": "瑞舍夫戰車",
                "type": "cavalry",
                "attack": 110,
                "defense_infantry": 120,
                "defense_cavalry": 150,
                "upkeep": 3,
                "cost": {"wood": 450, "clay": 560, "iron": 610, "crop": 180},
                "training_time": "0:53:20",
                "role": "重型單位，攻防兼備",
            },
            "ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 60,
                "defense_infantry": 30,
                "defense_cavalry": 75,
                "upkeep": 3,
                "cost": {"wood": 995, "clay": 575, "iron": 340, "crop": 80},
                "training_time": "1:10:00",
                "role": "破壞城牆",
            },
            "stone_catapult": {
                "name_zh": "投石類攻城武器",
                "type": "siege",
                "attack": 55,
                "defense_infantry": 65,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 980, "clay": 1510, "iron": 660, "crop": 100},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "nomarch": {
                "name_zh": "州長",
                "type": "special",
                "attack": 50,
                "defense_infantry": 50,
                "defense_cavalry": 50,
                "upkeep": 5,
                "cost": {"wood": 34000, "clay": 50000, "iron": 34000, "crop": 42000},
                "training_time": "19:35:00",
                "role": "降低敵方村莊忠誠度 20-25%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 0,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 4400, "clay": 5600, "iron": 4200, "crop": 3900},
                "training_time": "8:53:20",
                "role": "建立新村莊",
            },
        },
    },
    "huns": {
        "name_zh": "匈奴",
        "name_en": "Huns",
        "description": "以騎兵為主的兇猛部落，速度快但防禦弱",
        "playstyle": "適合有經驗的進攻型玩家",
        "strengths": [
            "擁有最快的偵察兵（探子）",
            "騎兵強大且速度快",
            "商人速度最快（20格/小時）",
            "英雄騎乘時讓騎兵軍隊+3速度",
        ],
        "weaknesses": [
            "防禦單位弱",
            "城牆（簡易牆）防禦效果差",
            "需要依賴聯盟支援防禦",
        ],
        "special_building": {
            "name": "指揮中心 (Command Center)",
            "effect": "提供額外的擴張選項",
        },
        "merchant": {"capacity": 500, "speed": 20},
        "hero_bonus": "騎乘的英雄讓騎兵軍隊+3速度（軍隊不能包含步兵）",
        "recommended_defense_ratio": "依賴聯盟支援",
        "troops": {
            "mercenary": {
                "name_zh": "僱傭兵",
                "type": "infantry",
                "attack": 35,
                "defense_infantry": 40,
                "defense_cavalry": 30,
                "upkeep": 1,
                "cost": {"wood": 130, "clay": 80, "iron": 40, "crop": 50},
                "training_time": "0:14:00",
                "role": "基礎步兵",
            },
            "bowman": {
                "name_zh": "弓箭手",
                "type": "infantry",
                "attack": 50,
                "defense_infantry": 30,
                "defense_cavalry": 10,
                "upkeep": 1,
                "cost": {"wood": 140, "clay": 110, "iron": 60, "crop": 60},
                "training_time": "0:18:00",
                "role": "遠程攻擊步兵",
            },
            "spotter": {
                "name_zh": "探子",
                "type": "cavalry",
                "attack": 0,
                "defense_infantry": 20,
                "defense_cavalry": 10,
                "upkeep": 1,
                "cost": {"wood": 170, "clay": 150, "iron": 30, "crop": 50},
                "training_time": "0:20:00",
                "role": "最快的偵察兵",
            },
            "steppe_rider": {
                "name_zh": "草原騎士",
                "type": "cavalry",
                "attack": 100,
                "defense_infantry": 40,
                "defense_cavalry": 30,
                "upkeep": 2,
                "cost": {"wood": 330, "clay": 300, "iron": 260, "crop": 100},
                "training_time": "0:32:00",
                "role": "快速攻擊騎兵",
            },
            "marksman": {
                "name_zh": "神射手",
                "type": "cavalry",
                "attack": 80,
                "defense_infantry": 50,
                "defense_cavalry": 50,
                "upkeep": 2,
                "cost": {"wood": 360, "clay": 330, "iron": 280, "crop": 120},
                "training_time": "0:40:00",
                "role": "騎射手",
            },
            "marauder": {
                "name_zh": "掠奪者",
                "type": "cavalry",
                "attack": 180,
                "defense_infantry": 60,
                "defense_cavalry": 70,
                "upkeep": 3,
                "cost": {"wood": 520, "clay": 600, "iron": 620, "crop": 180},
                "training_time": "0:52:00",
                "role": "重騎兵",
            },
            "ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 70,
                "defense_infantry": 30,
                "defense_cavalry": 105,
                "upkeep": 3,
                "cost": {"wood": 1060, "clay": 330, "iron": 360, "crop": 70},
                "training_time": "1:05:00",
                "role": "破壞城牆",
            },
            "catapult": {
                "name_zh": "投石類攻城武器",
                "type": "siege",
                "attack": 55,
                "defense_infantry": 50,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 950, "clay": 1280, "iron": 620, "crop": 60},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "logades": {
                "name_zh": "重步兵",
                "type": "special",
                "attack": 60,
                "defense_infantry": 40,
                "defense_cavalry": 60,
                "upkeep": 5,
                "cost": {"wood": 36500, "clay": 30500, "iron": 27000, "crop": 26000},
                "training_time": "17:05:00",
                "role": "降低敵方村莊忠誠度 15-30%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 10,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 5040, "clay": 3880, "iron": 4040, "crop": 4600},
                "training_time": "7:26:40",
                "role": "建立新村莊",
            },
        },
    },
    "spartans": {
        "name_zh": "斯巴達",
        "name_en": "Spartans",
        "description": "擁有遊戲中最強大的單位，但訓練慢且成本高",
        "playstyle": "適合有耐心的玩家，專注後期發展",
        "strengths": [
            "部隊非常強大且糧食效率高",
            "阿斯克勒庇俄斯神殿可恢復60%陣亡部隊",
            "英雄使用斯巴達武器時+50%力量加成",
            "強大的後期潛力",
        ],
        "weaknesses": [
            "訓練時間長",
            "單位成本高",
            "防禦牆較弱",
        ],
        "special_building": {
            "name": "阿斯克勒庇俄斯神殿 (Asclepeion)",
            "effect": "可恢復最多60%戰鬥中陣亡的部隊",
        },
        "merchant": {"capacity": 500, "speed": 14},
        "hero_bonus": "使用斯巴達武器時獲得+50%力量加成",
        "recommended_defense_ratio": "根據情況靈活配置",
        # 兵種數值照 ASIA x1 遊戲內說明（evidence/asia_x1_manual_spartans_2026-10-11.json）
        "troops": {
            "hoplite": {
                "name_zh": "裝甲步兵",
                "type": "infantry",
                "attack": 50,
                "defense_infantry": 35,
                "defense_cavalry": 30,
                "upkeep": 1,
                "cost": {"wood": 110, "clay": 185, "iron": 110, "crop": 35},
                "training_time": "0:28:20",
                "role": "主力步兵",
            },
            "sentinel": {
                "name_zh": "哨兵",
                "type": "infantry",
                "attack": 0,
                "defense_infantry": 40,
                "defense_cavalry": 22,
                "upkeep": 1,
                "cost": {"wood": 185, "clay": 150, "iron": 35, "crop": 75},
                "training_time": "0:20:32",
                "role": "偵察兵，最強的反偵察能力但也最貴",
            },
            "shieldsman": {
                "name_zh": "盾牌手",
                "type": "infantry",
                "attack": 40,
                "defense_infantry": 85,
                "defense_cavalry": 45,
                "upkeep": 1,
                "cost": {"wood": 145, "clay": 95, "iron": 245, "crop": 45},
                "training_time": "0:32:16",
                "role": "防禦步兵",
            },
            "twirler": {
                "name_zh": "雙鋼泰瑞恩",
                "type": "infantry",
                "attack": 90,
                "defense_infantry": 55,
                "defense_cavalry": 40,
                "upkeep": 1,
                "cost": {"wood": 130, "clay": 200, "iron": 400, "crop": 65},
                "training_time": "0:35:12",
                "role": "強力攻擊步兵",
            },
            "elpida_rider": {
                "name_zh": "爾必達騎士",
                "type": "cavalry",
                "attack": 55,
                "defense_infantry": 120,
                "defense_cavalry": 90,
                "upkeep": 2,
                "cost": {"wood": 555, "clay": 445, "iron": 330, "crop": 110},
                "training_time": "0:46:56",
                "role": "防禦騎兵",
            },
            "corinthian_crusher": {
                "name_zh": "科林斯破壞者",
                "type": "cavalry",
                "attack": 195,
                "defense_infantry": 80,
                "defense_cavalry": 75,
                "upkeep": 3,
                "cost": {"wood": 660, "clay": 495, "iron": 995, "crop": 165},
                "training_time": "0:57:12",
                "role": "重騎兵",
            },
            "ram": {
                "name_zh": "破城槌",
                "type": "siege",
                "attack": 65,
                "defense_infantry": 30,
                "defense_cavalry": 80,
                "upkeep": 3,
                "cost": {"wood": 525, "clay": 260, "iron": 790, "crop": 130},
                "training_time": "1:17:00",
                "role": "破壞城牆",
            },
            "catapult": {
                "name_zh": "賴達投石機",
                "type": "siege",
                "attack": 50,
                "defense_infantry": 60,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 550, "clay": 1240, "iron": 825, "crop": 135},
                # RoG 限定：社群資料（一般世界）是 2:45:00（evidence/crosscheck_spartans_vikings_2026-10-11.json）
                "training_time": "2:30:00（ASIA x1 年度特別世界實測；一般世界待驗證，社群資料 2:45:00）",
                "role": "破壞建築物",
            },
            "ephor": {
                "name_zh": "五長官",
                "type": "special",
                "attack": 40,
                "defense_infantry": 60,
                "defense_cavalry": 40,
                "upkeep": 4,
                "cost": {"wood": 33450, "clay": 30665, "iron": 36240, "crop": 13935},
                "training_time": "21:32:30（ASIA x1 年度特別世界實測；一般世界待驗證，社群資料 8:00:00）",
                "role": "降低敵方村莊忠誠度 20-25%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 10,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 5115, "clay": 5580, "iron": 6045, "crop": 3255},
                "training_time": "9:28:20",
                "role": "建立新村莊",
            },
        },
    },
    "vikings": {
        "name_zh": "維京",
        "name_en": "Vikings",
        "description": "以掠奪和海戰為主，狂戰士擁有獨特的死亡反擊能力",
        "playstyle": "適合喜歡掠奪的進攻型玩家",
        "strengths": [
            "維京港口可讓船隻以24格/小時速度掠奪",
            "狂戰士死亡時會帶走一個敵方單位",
            "英雄在攻擊和掠奪時可降低5%忠誠度",
            "商人速度較快（18格/小時）",
        ],
        "weaknesses": [
            "狂戰士糧食消耗高（2糧）",
            "整體訓練成本較高",
        ],
        "special_building": {
            "name": "維京港口 (Viking Harbor)",
            "effect": "可建造更快的掠奪船（24格/小時，其他部族18格/小時）",
        },
        "merchant": {"capacity": 750, "speed": 18},
        "hero_bonus": "攻擊和掠奪時可降低敵方村莊5%忠誠度",
        "recommended_defense_ratio": "以侍衛騎士為主",
        "troops": {
            "thrall": {
                "name_zh": "奴僕",
                "type": "infantry",
                "attack": 45,
                "defense_infantry": 22,
                "defense_cavalry": 5,
                "upkeep": 1,
                "cost": {"wood": 95, "clay": 80, "iron": 50, "crop": 40},
                "training_time": "0:13:20",
                "role": "基礎掠奪步兵",
            },
            "shield_maiden": {
                "name_zh": "盾女",
                "type": "infantry",
                "attack": 20,
                "defense_infantry": 50,
                "defense_cavalry": 30,
                "upkeep": 1,
                "cost": {"wood": 120, "clay": 100, "iron": 60, "crop": 40},
                "training_time": "0:18:00",
                "role": "防禦步兵",
            },
            "berserker": {
                "name_zh": "狂戰士",
                "type": "infantry",
                "attack": 70,
                "defense_infantry": 30,
                "defense_cavalry": 25,
                "upkeep": 2,
                "cost": {"wood": 265, "clay": 230, "iron": 155, "crop": 75},
                "training_time": "0:25:50",
                "role": "特殊攻擊步兵，死亡時帶走一個敵方單位",
            },
            "scout": {
                "name_zh": "海姆達爾之眼",
                "type": "cavalry",
                "attack": 0,
                "defense_infantry": 10,
                "defense_cavalry": 5,
                "upkeep": 1,
                "cost": {"wood": 140, "clay": 130, "iron": 40, "crop": 40},
                "training_time": "0:18:40",
                "role": "偵察兵",
            },
            "huskarl_rider": {
                "name_zh": "侍衛騎士",
                "type": "cavalry",
                "attack": 45,
                "defense_infantry": 95,
                "defense_cavalry": 100,
                "upkeep": 2,
                "cost": {"wood": 385, "clay": 340, "iron": 230, "crop": 100},
                "training_time": "0:44:10",
                "role": "全能防禦騎兵",
            },
            "valkyrjas_blessing": {
                "name_zh": "女武神之賜",
                "type": "cavalry",
                "attack": 160,
                "defense_infantry": 50,
                "defense_cavalry": 75,
                "upkeep": 2,
                "cost": {"wood": 560, "clay": 580, "iron": 355, "crop": 130},
                "training_time": "0:51:00",
                "role": "攻擊騎兵",
            },
            "ram": {
                "name_zh": "衝撞車／破城槌",
                "type": "siege",
                "attack": 65,
                "defense_infantry": 30,
                "defense_cavalry": 80,
                "upkeep": 3,
                "cost": {"wood": 620, "clay": 560, "iron": 420, "crop": 120},
                "training_time": "1:10:00",
                "role": "破壞城牆",
            },
            "catapult": {
                "name_zh": "投石類攻城武器",
                "type": "siege",
                "attack": 50,
                "defense_infantry": 60,
                "defense_cavalry": 10,
                "upkeep": 6,
                "cost": {"wood": 940, "clay": 1260, "iron": 440, "crop": 120},
                "training_time": "2:30:00",
                "role": "破壞建築物",
            },
            "jarl": {
                "name_zh": "領主",
                "type": "special",
                "attack": 40,
                "defense_infantry": 40,
                "defense_cavalry": 60,
                "upkeep": 4,
                "cost": {"wood": 37000, "clay": 32000, "iron": 22000, "crop": 23300},
                "training_time": "19:35:00",
                "role": "降低敵方村莊忠誠度 15-30%",
            },
            "settler": {
                "name_zh": "開拓者",
                "type": "special",
                "attack": 10,
                "defense_infantry": 80,
                "defense_cavalry": 80,
                "upkeep": 1,
                "cost": {"wood": 6300, "clay": 5000, "iron": 4200, "crop": 4500},
                "training_time": "8:36:40",
                "role": "建立新村莊",
            },
        },
    },
}


def _apply_unit_speeds() -> None:
    """把產生器的兵種速度、運載量與出處帶入 TRIBES_DATA（唯一一份速度／運載量資料）.

    部族名、兵種名也照遊戲內名稱表（ingame_names.json）；舊名放 aliases_zh，只給搜尋用。
    """
    data = json.loads(UNIT_SPEEDS_PATH.read_text(encoding="utf-8"))
    names = json.loads(INGAME_NAMES_PATH.read_text(encoding="utf-8"))
    for tribe, rows in data["tribes"].items():
        TRIBES_DATA[tribe]["name_zh"] = names["tribes"][tribe]["zh"]
        troops = TRIBES_DATA[tribe]["troops"]
        for row in rows:
            troop = troops[row["kb_id"]]
            unit = names["units"][row["troop_id"]]
            troop["name_zh"] = unit["zh"]
            troop["aliases_zh"] = unit["aliases"]
            troop["speed"] = row["speed"]
            troop["speed_source"] = row["source"]
            # 運載量也照產生檔（P0-23：前端、troops.json 同一份）
            troop["capacity"] = row["carry"]
            troop["capacity_source"] = row["carry_source"]


_apply_unit_speeds()


def get_tribe_info(tribe_name: str) -> dict | None:
    """取得部族資訊."""
    tribe_key = tribe_name.lower()
    # 支援中文名稱查詢
    name_mapping = {
        "羅馬": "romans",
        "高盧": "gauls",
        "條頓": "teutons",  # 舊名，只給查詢用（輸出一律是遊戲內名稱）
        "日耳曼": "teutons",
        "日耳曼人": "teutons",
        "埃及": "egyptians",
        "匈奴": "huns",
        "斯巴達": "spartans",
        "維京": "vikings",
    }
    if tribe_key in name_mapping:
        tribe_key = name_mapping[tribe_key]
    return TRIBES_DATA.get(tribe_key)


def get_all_tribes() -> dict:
    """取得所有部族資訊."""
    return TRIBES_DATA


def get_troop_info(tribe_name: str, troop_name: str) -> dict | None:
    """取得特定兵種資訊."""
    tribe = get_tribe_info(tribe_name)
    if not tribe:
        return None
    troops = tribe.get("troops", {})
    if isinstance(troops, dict):
        result = troops.get(troop_name.lower())
        if isinstance(result, dict):
            return result
    return None
